### ISSUE TITLE
husky postinstall시 권한설정 이슈

### ISSUE THREAD

**Issue by shaqok** [preonboarding-internship/qna-10th#1]
husky + lint-staged를 설정하면서 notion에 적힌대로 husky를 설정했었습니다.
`package.json`에 `postinstall`을 설정하고 제가 클론 받아서 `npm install` 을 하면서 `husky`도 install 되었는데요.

커밋을 하는 단계에서 이런 메시지가 나오면서 hook이 작동하지 않더라구요:
```
hint: the '.husky/pre-commit' hook was ignored because it's not set as executable.
hint: You can disable this warning with git config advice.ignoredHook false.
```

검색을 해보니 맥이나 리눅스에서 주로 발생하는 것 같고 `npm install`후에 `.husky/`폴더의 실행권한을 `chmod ug+x .husky/*` 커맨드로 변경하라는 답변들이 있었는데요, 혹시 이렇게 메뉴얼하게 변경해주는 방법 말고 다른 OS들에서도 잘 작동시키는 방법을 아시는지 궁금합니다. 맥은 쓰시는 다른 팀원분은 새로 클론을 받았더니 해결됐다는 분도 계셨습니다.

이슈 링크 첨부할게요: https://github.com/typicode/husky/issues/1177

**Comment by walking-sunset** [comment]
안녕하세요 대연님,

일단 이슈 찾아보시고, 링크 첨부하셔서 질문하신 것 너무 좋네요 :)

해당 이슈를 확인해보니 https://github.com/typicode/husky/issues/1177#issuecomment-1454909623 이 코멘트에서 분석한 바에 따르면, 윈도우에서는 파일의 실행가능권한(executable)을 추적하지 않는데, 유닉스기반(리눅스 및 맥)에서는 해당 권한에 따라서 파일이 실행가능한지를 판단하기 때문에 발생하는 문제로 보이네요, 그래서 윈도우에서 husky 초기세팅을 하면 실행권한이 빠진 상태로 git에 커밋이 되고, 이후 유닉스 운영체제를 사용하시는 팀원들이 이 파일을 실행하려고 하면 문제가 생기는 경우로 판단됩니다.

그리고, 이는 운영체제의 특성에 따른 부분이라서 husky 측에서도 아직 이슈를 해결하지 못하고, 계속해서 open 된 상태로 남아있는 것 같네요, 이슈 내용 및 코멘트 확인해본 결과 이미 초기세팅을 한 경우에는 unix 시스템에서 파일의 권한을 수정 후 커밋하면 해결할 수 있는 것으로 보입니다.

저렇게 메뉴얼하게 수정 안하고 진행할 수 있는 방식으로는, Unix 기반 운영체제에서 husky 관련 초기세팅을 진행하는 것이 제일 간단할 것 같다는 생각이 드네요... 😂

제 개인적인 의견은 이슈가 해결되기 전까지는 이후에 진행하는 프로젝트부터는 유닉스 운영체제에서 초기세팅을 진행하시고, 이미 세팅된 프로젝트에서는 권한 수정 후 커밋하시는 방향으로 진행하시는게 최선의 방향성으로 생각됩니다.
