### ISSUE TITLE
CORS 에러 질문 드립니다!

### ISSUE THREAD

**Issue by Yena-Yun** [preonboarding-internship/qna-10th#2]
기업 과제의 API 호출 중 CORS 에러가 발생했습니다.

![image](https://user-images.githubusercontent.com/68722179/235674395-65b38280-7a16-4076-ab00-8ff3e78d6473.png)

axios 헤더 쪽에 withCredentials: true를 설정하고,
config 파일에서는 proxy 설정을 추가했습니다. (개인 로컬에서 Vite 사용중입니다)

![image](https://user-images.githubusercontent.com/68722179/235675765-39b22814-61f0-468b-92f2-8ea7e1838bd4.png)

Network 탭에서 상태코드는 200번이지만 여전히 에러인 상태입니다.
![image](https://user-images.githubusercontent.com/68722179/235674982-e84b6400-63a5-421e-90c5-209853075ed3.png)

콘솔 에러 메시지의 'Access to XMLHttpRequest at ~' 옆 경로를 클릭했을 때 이동하는 화면에서는 
입력값에 맞는 데이터가 잘 응답된 것을 확인할 수 있었습니다.

![image](https://user-images.githubusercontent.com/68722179/235677059-e5e69219-c2b8-4dc2-838e-878573f0fd69.png)

응답된 데이터를 브라우저에서 받아오려면 어떻게 해야 할까요?
<BR/>
이 부분을 프론트쪽에서 해결하는 것이 과제의 의도에 포함인지, 
아니면 서버쪽에서 설정을 바꿔주실 수 있는 부분인지 여쭤봅니다.

**Comment by walking-sunset** [comment]
기업 과제 자체에서 의도된 부분은 아니나, 프론트단에서 임의로 CORS를 우회하는 방식으로 진행해주시면 됩니다 :)
