### ISSUE TITLE
과제 예시 사진과 클론 대상 웹 사이트 화면과 UI 차이 문제 

### ISSUE THREAD

**Issue by liketiger** [preonboarding-internship/qna-10th#3]
안녕하세요 다름이 아니라 노션 과제 설명 페이지에는

![스크린샷 2023-05-02 오후 11 54 50](https://user-images.githubusercontent.com/50165633/235703969-f2e8ef75-1705-4594-ba06-b63346ecce45.png)

위와 같은 예시를 제공하고 있는데
클론 해야할 실제 웹사이트는 아래와 같이

![스크린샷 2023-05-02 오후 11 55 49](https://user-images.githubusercontent.com/50165633/235704244-8962ba34-8a70-4751-84cd-0265b7a0da4a.png)

이렇게 추천 검색어 위에 현재 치고 있는 검색 내용을 추가로 보여줘서요.

둘 중 어느 것으로 UI를 맞춰야 할지 궁금하여 문의드립니다.

**Comment by walking-sunset** [comment]
UI는 둘 중 어느 형태로 진행하셔도 무방합니다. 둘 중 편하신 UI로 진행해주시면 되겠습니다 :)
