### ISSUE TITLE
캐싱 영역 구현에서 검색 시 어떤 것을 캐싱해야 하나요?

### ISSUE THREAD

**Issue by Plu457** [preonboarding-internship/qna-10th#4]
캐싱 영역을 구현하려고 있는데, 이해가 잘 되지 않아서 질문드립니다. 예를 들어, '갑상선암'을 검색하면 어떤 것을 캐싱해야 할까요? 강의 영상을 보았지만, 계속해서 반환 값을 캐싱하라고 하던데, 반환 값은 [{name: "갑상선암", id: 4373}, {name: "갑상선암종", id: 4375}] 이런 형태로 나옵니다. 그렇다면 이 반환 값들을 모두 캐싱해야 할까요? 아니면 '갑상선암'이라는 검색어를 캐싱해야 할까요?

**Comment by powercording** [comment]
키와 데이터 모두 캐싱을 해야한다고 생각합니다. 

캐싱을 구현하는 의미를 생각하면 같은 키값으로 검색이 중복해서 일어날때 서버자원을 소비하지 않고 저장된 데이터를 활용해야 하므로, 

리퀘스트를 보낸 요청을 구분할수 있는 키와 응답 데이터 모두를 캐싱하는것이 맞다고 생각됩니다.

**Comment by 1yoouoo** [comment]
키와 밸류 모두 캐싱하라고 하는 거 같아요.

그 이후에 같은 값이 입력이 됐을 때 캐싱한 밸류를 보여줄 수 있게함으로 리소스를 줄일 수 있도록 하는 거 같네요

**Comment by walking-sunset** [comment]
@powercording @1yoouoo 👍👍
