### ISSUE TITLE
배포 환경에서의 CORS 관련

### ISSUE THREAD

**Issue by Smang09** [preonboarding-internship/qna-10th#5]
개발 환경에서는 proxy를 설정하여 우회하는 방법으로 CORS를 해결했는데, 배포 환경에서 발생하는 에러도 따로 처리를 해야할까요? 아니면 배포 링크를 영상으로 대체 가능한가요?

**Comment by 1yoouoo** [comment]
저도 그 부분이 궁금했습니다.

**Comment by walking-sunset** [comment]
배포는 CORS 관련없이 진행해주시면 됩니다, 네트워크 요청 시 CORS 발생하는 상황이더라도 필요하면 제가 브라우저단에서 CORS 동작 끄고 확인하면 되니까 CORS 문제는 따로 처리 안하고 그냥 배포하셔도 됩니다~!

다만, 제3자가 봤을 때는 혼란스럽거나 오해할 수 있기에 관련된 내용은 README에 적어주시는 것이 좋겠네요 :)
