### ISSUE TITLE
의존성 주입관련 질문입니다.

### ISSUE THREAD

**Issue by ad105geppetto** [preonboarding-internship/qna-10th#6]
안녕하세요 멘토님!

강의를 보며 다시 복습을 하고 있는데, context api 사용시 의존성 주입이 된다는 부분이 잘 이해가 안되어서요.

함수형 컴포넌트의 경우 의존성 주입이 인자를 통해 이루어진다고 알고 있습니다.

그런데 components/Todos.js 에서 함수선언시, Todos 함수형 컴포넌트의 인자로는 어떠한 것도 받지 않고 useTodo 라는 커스텀 훅으로 props를 관리하고 있습니다. 이 경우 Todos 컴포넌트는 의존성 주입이 되지 않았다고 보는게 맞을 것 같은데 맞을까요??

제가 이해한게 틀리다면, context api 사용시 의존성 주입이 어디에서 수행되었는지 알려주신다면 감사하겠습니다.

**Comment by liketiger** [comment]
저도 궁금하네요 특히 상태랑 같이 전달하는게 아니라면 굳이 Context API 쓸 필요 없이 주입할 애들 그냥 별도의 파일로 만들어 놓고 각 컴포넌트들에서 import 해와서 쓰면 된다고 생각합니다. 어차피 Context API도 useContext import 해와서 써서...

**Comment by Yena-Yun** [comment]
저는 이 질문의 내용이랑 조금 다른 방향이긴 한데,
실습 코드 복습할 때 Todo가 변경되면 Auth(인풋, signin/signup 버튼) 부분도
같이 리렌더링 되더라고요 (브라우저 하이라이트로 확인했습니다)

이 현상의 원인이 무엇일지, 어떻게 최적화할 수 있을지 궁금해서 같은 곳에 질문 남겨봅니다

* 원인 관련해서 제 추측인데,
혹시 index.js에서 AuthProvider 안에 TodoProvider가 포함되어서 일까요?
둘을 나눠보는 방법을 생각해보니 Auth안에 App, Todo 안에 App
이렇게 들어가는 방법이 떠올랐는데 이건 또 아닌 것 같네요 😂😂

**Comment by powercording** [comment]
```js
root.render(
  <AuthProvider authService={authService}>
    <TodoProvider todoService={todoService}>
      <App />
    </TodoProvider>
  </AuthProvider>
);
```

프로바이더도 컴포넌트이니 해당 Provider 를 리턴하는 context 에서 state변경이  일어날시 Children ( App  컴포넌트 ) 리랜더링 되는게 아닐까 생각해봅니당.

```js

// TodoContext

export const TodoProvider = ({ children, todoService }) => {
  const [todos, setTodos] = useState([]);

  useEffect(() => {
    todoService.get().then(setTodos);
  }, [todoService, setTodos]);

  const create = async (newTodo) => {
    const todo = await todoService.create(newTodo);
    setTodos([...todos, todo]);
  };

  return (
    <TodoContext.Provider
      value={{
        todos,
        create,
      }}
    >
      {children}
    </TodoContext.Provider>
  );
};
```

> 저는 이 질문의 내용이랑 조금 다른 방향이긴 한데, 실습 코드 복습할 때 Todo가 변경되면 Auth(인풋, signin/signup 버튼) 부분도 같이 리렌더링 되더라고요 (브라우저 하이라이트로 확인했습니다)
> 
> 이 현상의 원인이 무엇일지, 어떻게 최적화할 수 있을지 궁금해서 같은 곳에 질문 남겨봅니다
> 
> * 원인 관련해서 제 추측인데,
>   혹시 index.js에서 AuthProvider 안에 TodoProvider가 포함되어서 일까요?
>   둘을 나눠보는 방법을 생각해보니 Auth안에 App, Todo 안에 App
>   이렇게 들어가는 방법이 떠올랐는데 이건 또 아닌 것 같네요 😂😂

**Comment by liketiger** [comment]
저는 AuthContext와 TodoContext에서 각각 state와 setState를 만들어 각자의 provider로 뿌린뒤 Auth, Todo 각 컴포넌트에서 setState 트리거 시키니 정확히 해당 컴포넌트만 리렌더링 됩니다.
또한 Auth, Todo 컴포넌트에서 상태를 새로 만들고 setState 트리거 시켜도 해당 컴포넌트만 리렌더링 되고요
저는 console.log로 확인했습니다

**Comment by yeonuk-hwang** [comment]
> 안녕하세요 멘토님!
> 
> 강의를 보며 다시 복습을 하고 있는데, context api 사용시 의존성 주입이 된다는 부분이 잘 이해가 안되어서요.
> 
> 함수형 컴포넌트의 경우 의존성 주입이 인자를 통해 이루어진다고 알고 있습니다.
> 
> 그런데 components/Todos.js 에서 함수선언시, Todos 함수형 컴포넌트의 인자로는 어떠한 것도 받지 않고 useTodo 라는 커스텀 훅으로 props를 관리하고 있습니다. 이 경우 Todos 컴포넌트는 의존성 주입이 되지 않았다고 보는게 맞을 것 같은데 맞을까요??
> 
> 제가 이해한게 틀리다면, context api 사용시 의존성 주입이 어디에서 수행되었는지 알려주신다면 감사하겠습니다.

안녕하세요,

일단 결론은 useTodo를 사용하는 것이 바로 의존성을 주입받는 과정입니다.

1. 컴포넌트의 경우 인자(prop)으로 의존성을 주입받는다.

2. 하지만 컴포넌트의 트리가 깊어질 경우 prop으로 의존성을 전달하기 위해서 많은 props drilling이 발생한다.

3. 그래서, 필요한 인자를 drilling 없이 전달할 수 있는 context api를 사용한다.

4. useTodo라는 훅은 context api에서 전달해준 value를 꺼내오는 훅이기 때문에 의존성을 주입받는 것이다.

위의 과정으로 이해하시면 될 것 같습니다 :)

**Comment by yeonuk-hwang** [comment]
> 저도 궁금하네요 특히 상태랑 같이 전달하는게 아니라면 굳이 Context API 쓸 필요 없이 주입할 애들 그냥 별도의 파일로 만들어 놓고 각 컴포넌트들에서 import 해와서 쓰면 된다고 생각합니다. 어차피 Context API도 useContext import 해와서 써서...

말씀하신 상황에서는 이렇게 진행해도 되지만, import로 진행할 경우 아래와 같은 문제점이 있습니다.

1. 커스텀훅의 형태로 꺼내올 수 없게 된다 (커스텀 훅 형태로 구체를 숨긴 뒤에 구체적인 동작을 추후에 바꾸는 식으로 변경이 발생할 때 문제가 생길 것 같네요)

2. import는 각 파일마다 해줘야 한다. 만약 의존성이 변경될 일이 생기면 각 파일마다 돌아가면서 import를 변경해줘야 하는 소요가 발생한다. 하지만 context api를 통해서 의존성을 주입하게 되면 실습코드를 예로 들자면 index.js에서 주입되는 의존성만 변경하면 다른 파일들에서는 아무런 코드의 변화 없이 동작을 변경할 수 있게 됩니다 (이 이유가 state를 쓰지 않음에도 import를 하지 않고, 컨텍스트를 통해서 전달하는 가장 큰 이유입니다)

**Comment by yeonuk-hwang** [comment]
@powercording @Yena-Yun 

실습코드에서는 todos 관련 state가 변했을 때 Auth는 리렌더링 되지 않는 것으로 확인됩니다!, 리렌더링 되는 현상을 발견했다면 해당 코드를 올려주시면 어떤 문제인지 답변드릴게요~!

일단, children을 감싸고 있는 컴포넌트의 경우 그냥 chidlren이란 이름의 prop을 받은것과 똑같기에, 감싸고 있는 컴포넌트가 렌더링된다고 해도, children에 리렌더링은 발생하지 않습니다. 그래서 실습코드 구조에서는 Provider가 App을 감싸고 있는 형태이지만, Provider의 state가 변경되더라도 실제 useContext 등으로 해당 컨텍스트를 구독하고 있는 컴포넌트만 리렌더링 되는 방식으로 동작을 하고 있는 형태입니다!

**Comment by yeonuk-hwang** [comment]
다들 적극적으로 토론하시는 모습 너무 좋네요 :) 💪

**Comment by Yena-Yun** [comment]
실습 코드 복습 과정에서 제가 뭔가 코드를 잘못 짰나봐요 ㅠㅠ
다시 확인해보겠습니다 답변 감사드려요~
