### ISSUE TITLE
로컬 캐싱 관련 질문

### ISSUE THREAD

**Issue by liketiger** [preonboarding-internship/qna-10th#7]
안녕하세요 멘토님 로컬 캐싱 관련해서 질문이 있어서요

In-memory 로컬 캐싱과 관련된 부분인데 in-memory로 로컬 캐싱을 구현할 때 캐시 데이터를 저장할 방법으로 3가지가 있는 것 같은데 각자 장단점이 있는 것 같아 현업에서는 어떤 방식을 사용하는지 어떤 방식이 Best-practice에 가까운지 궁금하여 문의드립니다.

[useState]
useState의 경우 컴포넌트가 리렌더링 될 때 저장된 값이 매번 초기화 되지 않는 점이 있지만 값을 변경할 떄 setState를 사용해야되고 그럼 리렌더링이 발생하는 문제가 있는 것 같습니다. 물론 저장된 캐시 값이 변한다고 UI가 변경되는 부분은 없어서 diff 알고리즘에 의해 화면이 변하는 건 없지만 캐시 값이 변경될때마다 재평가(재실행?)하는 것 자체가 성능적으로 문제가 될 수 있다고 생각합니다.
ex) const [cache, setCache] = useState({});

[useRef] 
useRef로 변수를 만들면 저장된 값을 변경해도 리렌더링 되지 않고 다른 요인에 의해 리렌더링이 되더라도 저장된 값을 유지할 수 있어 좋아보입니다. 하지만 useRef는 DOM 조작에 사용되기 위해 만들어진 것이고 변수 사용 목적으로는 지양하라는 글을 종종 봐서 캐시 값을 저장하려는 변수 목적으로 로컬 캐싱에 사용하는게 적합한지 의문이 듭니다.
ex ) const cache = useRef({});

[JS Object]
자바스크립트 객체 리터럴로 만들되 리렌더링시 매번 초기화되는 것을 피하기위해 다른 파일에 초기화한 후 export하여 가져다 쓰는 방식으로 하면 좋을 것 같습니다. 하지만 리액트 스타일에 맞지 않고 Vanilla JS 방식에 더 어울린다고 생각하여 적합한지 모르겠습니다.
ex) const obj = {};

위 3가지 방식 모두 잘 동작하는 것을 확인하였습니다.
현업에서 in-memory 로컬 캐싱을 구현하는 일이 있을 지 모르겠지만 만약 있다면 위 3가지 방식중에 어떤 방식을 주로 사용하고 그 이유가 무엇인가요?
감사합니다.

두 번째 질문은 다른 곳에서 답변 해주셔서 삭제했습니다

**Comment by yeonuk-hwang** [comment]
안녕하세요, 성재님

일단 현업에서는 직접 캐싱 기능을 구현하기보다는 캐싱 기능이 포함되어 있는 라이브러리를 사용하는 형태로 진행하는 경우가 일반적입니다. 왜냐하면 기본적인 캐싱 이외에도 수많은 캐싱에 대한 옵션들이 제공되어야 하기에 이를 직접 구현하기보다는 잘 구현된 라이브러리(react-query)등을 사용하는 것이 일반적인 방향입니다. 다만 캐싱에 대한 개념이나 직접 구현해본 경험이 있어야지 훨씬 더 잘 사용할 수 있습니다 :)

질문에 답변드리자면 관리하고자 하는 값이 렌더링과 연관된 값이라면 useState를 사용하는 것이 좋은 방향일 것 같네요. 렌더링에 연관을 시키려면 어쨌든 state를 변경시켜야 하고, 그렇게 되면 결국 Object, useRef로 관리하는 캐싱 값을 다시한번 state로 세팅하는 과정은 필연적으로 들어갈 것 같네요, 전 그런 과정은 일반적인 상황에서는 불필요하다고 생각하기에 바로 변하면 리렌더링이 되어야 하는 값일 경우 바로 useState로 관리해주는 방향이 좋을 것 같네요

> 하지만 useRef는 DOM 조작에 사용되기 위해 만들어진 것이고 변수 사용 목적으로는 지양하라는 글을 종종 봐서

이 부분은 어디서 어떤 글을 보셨는진 모르겠지만... 모든 글을 여과없이 믿으면 안됩니다 😂 useRef의 경우 DOM 저장 뿐만 아니라 값을 저장하기 위한 용도로도 사용합니다. 다만, 값이 변했을 때 굳이 리렌더링이 필요하지 않은 값들을 관리할 때 좋은 선택지입니다. 따라서, 만약 특정 값을 관리하고 싶은데 변했을 때 리렌더링은 하고 싶지 않다면 useRef로 관리하는 것이 좋은 방향입니다!! 관련해서 [레퍼런스](https://react.dev/learn/referencing-values-with-refs)로 공식문서 링크 남겨둘테니 확인해보시면 좋을 것 같아요

**Comment by liketiger** [comment]
그렇군요 상황에 따라 useState와 useRef를 사용하면 되겠군요
답변 감사합니다.
